## easycron: Add cronjob
GET https://www.easycron.com/rest/add?token=MY_TOKEN_HERE&cron_expression=30 22 * * *&http_method=POST&posts=%7B%22token%22%3A%20%22ExponentPushToken%51234567890%5D%22%7D&url=SEND_PUSH_NOTIFICATION_URI

### easycron: get cronjobs

GET https://www.easycron.com/rest/list?token=MY_TOKEN_HERE

### Lambda: Report Inappropriate

POST http://localhost:3000/prod/reportinappropriate
Content-Type: application/json

{"messageId":"test messsage id", "reason": "bad content", "comment": "testme"}

### Lambda: Register Push Notifications
POST http://localhost:3000/prod/push-notifications/register
Content-Type: application/json

{
    "token": "ExponentPushToken[123456]",
    "hour": 4,
    "minute": 50
}

### Lambda: Unregister Push Notifications 
# Note: First register with .../register
POST http://localhost:3000/prod/push-notifications/unregister
Content-Type: application/json

{
    "token": "ExponentPushToken[123456]"
}

### Lambda: send push notification
POST http://localhost:3000/
Content-Type: application/json

{ 
    "token": "123456=="
}