service: youareawesomeapp
# app and org for use with dashboard.serverless.com
app: youareawesomeapp
org: prosingularity

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline # must come after typescript

# only deploy with specific Serverless version
frameworkVersion: ^2.2.0

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: prod

functions:
  reportInappropriate:
    handler: src/report-inappropriate.handler
    events:
      - http:
          path: "/reportinappropriate/"
          method: post

  registerPushNotif:
    handler: src/register-push-notification.handler
    events:
      - http:
          path: "/push-notifications/register/"
          method: post
    environment:
      CRON_JOB_NAME_PREFIX: "yaa-push-notifications-"

  unregisterPushNotif:
    handler: src/unregister-push-notification.handler
    events:
      - http:
          path: "/push-notifications/unregister/"
          method: post
    environment:
      CRON_JOB_NAME_PREFIX: "yaa-push-notifications-"
