# TODO cleanup by extracting vars to custom.locals.xy

service: youareawesomeapp
# app and org for use with dashboard.serverless.com
app: youareawesomeapp
org: prosingularity

# https://www.serverless.com/plugins/
plugins:
  - serverless-plugin-typescript
  - serverless-offline # must come after typescript
  - serverless-s3-sync
  - serverless-iam-roles-per-function
  - serverless-plugin-aws-alerts

# only deploy with specific Serverless version
frameworkVersion: ^2.48.0
configValidationMode: error
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "eu-central-1"}
  stage: ${opt:stage, "prod"}
  profile: serverless
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true

functions:
  reportInappropriate:
    handler: src/report-inappropriate/index.handler
    events:
      - http:
          path: "/reportinappropriate/"
          method: post
          request:
            schemas:
              application/json:
                schema: ${file(src/report-inappropriate/schema.json)}
                name: Report
                description: "Validation model to report inappropriate content"
    environment:
      SMTP_HOST: ${env:SMTP_HOST}
      SMTP_USERNAME: ${env:SMTP_USERNAME}
      SMTP_PASSWORD: ${env:SMTP_PASSWORD}
      SMTP_PORT: ${env:SMTP_PORT}
      USE_SSL: ${env:USE_SSL}
      TO_EMAILS_CSV: ${env:TO_EMAILS_CSV}
      FROM_ADDRESS: ${env:FROM_ADDRESS}

  writeContributionToGsheet:
    handler: src/contributions/index.writeContributionToGsheet
    events:
      - http:
          path: contributions
          method: post
          request:
            schemas:
              application/json:
                schema: ${file(src/contributions/contributions.schema.json)}
                name: PostContributionSchema
                description: "Validation model for Creating a Contribution"
    environment:
      CONTRIBUTIONS_SPREADSHEET_ID: ${env:CONTRIBUTIONS_SPREADSHEET_ID}
      CONTRIBUTIONS_GOOGLE_EMAIL: ${env:CONTRIBUTIONS_GOOGLE_EMAIL}
      CONTRIBUTIONS_GOOGLE_PRIVATE_KEY: ${env:CONTRIBUTIONS_GOOGLE_PRIVATE_KEY}

  registerPushNotif:
    handler: src/register-push-notification.handler
    events:
      - http:
          path: "/push-notifications/register/"
          method: post
    environment:
      CRON_JOB_NAME_PREFIX: "yaa-push-notifications-"
      PUSH_NOTIFICATIONS_BACKEND_URI:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - ${self:provider.region}
            - ".amazonaws.com/"
            - ${self:provider.stage}
            - /push-notifications/send/
            - ${env:SEND_PUSH_NOTIF_ENDPOINT}/
      EASY_CRON_API_TOKEN: ${env:EASY_CRON_API_TOKEN}
      HASH_PASSWORD: ${env:HASH_PASSWORD}
      SYMMETRIC_ENCRYPTION_KEY: ${env:SYMMETRIC_ENCRYPTION_KEY}

  unregisterPushNotif:
    handler: src/unregister-push-notification.handler
    events:
      - http:
          path: "/push-notifications/unregister/"
          method: post
    environment:
      CRON_JOB_NAME_PREFIX: "yaa-push-notifications-"
      EASY_CRON_API_TOKEN: ${env:EASY_CRON_API_TOKEN}
      HASH_PASSWORD: ${env:HASH_PASSWORD}

  sendPushNotif:
    handler: src/send-push-notification.handler
    events:
      - http:
          path: "/push-notifications/send/${env:SEND_PUSH_NOTIF_ENDPOINT}/"
          method: post
    environment:
      FETCH_POSTS_URI: ${env:FETCH_POSTS_URI}
      SYMMETRIC_ENCRYPTION_KEY: ${env:SYMMETRIC_ENCRYPTION_KEY}

  subscribePushNotif:
    handler: src/push-notifications/subscribe.handler
    events:
      - http:
          path: push-notifications/subscribe
          method: put
          request:
            schemas:
              application/json:
                schema: ${file(src/push-notifications/subscribe.schema.json)}
                name: PutPushNotifSubscription
                description: "Validation model for Creating or Updating Push Notification Subscriptions"
    environment:
      SUBSCRIPTION_TABLE: ${self:resources.Resources.PushNotifSubsTable.Properties.TableName}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - Fn::GetAtt: [PushNotifSubsTable, Arn]

  unsubPushNotif:
    handler: src/push-notifications/unsubscribe.handler
    events:
      - http:
          path: push-notifications/unsubscribe
          method: post
          request:
            schemas:
              application/json:
                schema: ${file(src/push-notifications/unsubscribe.schema.json)}
                name: PostPushNotifUnsubscribe
                description: "Validation model for Deleting Push Notification Subscriptions"
    environment:
      SUBSCRIPTION_TABLE: ${self:resources.Resources.PushNotifSubsTable.Properties.TableName}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt: [PushNotifSubsTable, Arn]

  # TODO #535 rename after migration
  sendPushNotif2:
    handler: src/push-notifications/send.handler
    events:
      - schedule:
          rate: rate(1 minute)
          description: Trigger lambda to send push notifications for the event time
          enabled: true
    environment:
      SUBSCRIPTION_TABLE: ${self:resources.Resources.PushNotifSubsTable.Properties.TableName}
      TICKET_TABLE: ${self:resources.Resources.PushNotifTicketsTable.Properties.TableName}
      AWESOME_MESSAGES_URI: "https://youareawesomeapp-current-message.s3.eu-central-1.amazonaws.com/messages.json"
      SUBSCRIPTIONS_BY_TIME_INDEX: ${self:resources.Resources.PushNotifSubsTable.Properties.GlobalSecondaryIndexes.0.IndexName}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:BatchWriteItem
        Resource:
          - Fn::GetAtt: [PushNotifTicketsTable, Arn]
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - Fn::GetAtt: [PushNotifSubsTable, Arn]
          - Fn::Join:
              - "/"
              - - Fn::GetAtt: [PushNotifSubsTable, Arn]
                - index
                - ${self:resources.Resources.PushNotifSubsTable.Properties.GlobalSecondaryIndexes.0.IndexName}

  exchangeTicketsForReceipts:
    handler: src/push-notifications/exchangeTicketsForReceipts.handler
    description: Read expo push notification success-tickets from dynamodb, exchange tickets for receipts with expo, write back error receipts and delete exchanged success tickets.
    events:
      - schedule:
          rate: rate(6 hours)
          description: Invoke lambda exchangeTicketsForReceipts
          enabled: true
    environment:
      TICKET_TABLE: ${self:resources.Resources.PushNotifTicketsTable.Properties.TableName}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:BatchWriteItem
        Resource:
          - Fn::GetAtt: [PushNotifTicketsTable, Arn]

  # Dnr = device not registered. had to shorten for iam
  handleDnrReceipts:
    handler: src/push-notifications/handleDeviceNotRegisteredReceipts.handler
    description: Read DeviceNotRegistered receipts from dynamodb and delete corresponding subscriptions. Finally delete handled receipts.
    events:
      - schedule:
          rate: rate(1 day)
          description: Invoke lambda handleDeviceNotRegisteredReceipts
          enabled: true
    environment:
      SUBSCRIPTION_TABLE: ${self:resources.Resources.PushNotifSubsTable.Properties.TableName}
      TICKET_TABLE: ${self:resources.Resources.PushNotifTicketsTable.Properties.TableName}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:BatchWriteItem
        Resource:
          - Fn::GetAtt: [PushNotifTicketsTable, Arn]
      - Effect: Allow
        Action:
          - dynamodb:BatchWriteItem
        Resource:
          - Fn::GetAtt: [PushNotifSubsTable, Arn]

  # only called via RPC => no events
  gsx2json:
    handler: src/gsx2json/index.handler
    environment:
      MESSAGES_SPREADSHEET_PUBLIC_ID: "2PACX-1vR83yDqRha4RaBeqzPnX6xh1I9PqndL2E_p8Ks9AzUp7KFae5fxlgWxDcVN4f8G41x3BtKQwz5M_ujM"

  exportMessagesToS3:
    handler: src/export-messages-to-s3.handler
    environment:
      GSX2JSON_LAMBDA_ARN:
        Fn::GetAtt: [Gsx2jsonLambdaFunction, Arn] # doesnt work with sls-offline
      BUCKET_NAME: ${self:service}-current-message
    events:
      # enable for dev
      # - http:
      #     path: "/manually-trigger-export-to-s3/"
      #     method: get
      - schedule:
          rate: rate(1 day)
          description: "Invoke export of Awesome Messages to S3 ${self:service}-current-messages"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource:
          - Fn::GetAtt: [Gsx2jsonLambdaFunction, Arn]
      - Effect: Allow
        Action:
          - s3:PutObject*
        Resource:
          - Fn::Join:
              - ""
              - - Fn::GetAtt: [CurrentMessageBucket, Arn]
                - "/*"

# https://www.serverless.com/framework/docs/providers/aws/guide/resources/
resources:
  Resources:
    CurrentMessageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-current-message

    legal:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-legal
        VersioningConfiguration:
          Status: Enabled

    PushNotifTicketsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: NotificationTickets-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    PushNotifSubsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: PushNotifSubs-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: expoPushToken
            AttributeType: S
          - AttributeName: time
            AttributeType: S
        KeySchema:
          - AttributeName: expoPushToken
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: TimeIndex
            KeySchema:
              - AttributeName: time
                KeyType: HASH
              - AttributeName: expoPushToken
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3

custom:
  # https://www.serverless.com/plugins/serverless-s3-sync
  s3Sync:
    - bucketName: ${self:service}-legal
      localDir: assets
      acl: public-read
      followSymlinks: false

  # https://www.serverless.com/plugins/serverless-plugin-aws-alerts
  alerts:
    stages:
      - prod
    topics:
      alarm:
        topic: ${self:service}-${self:provider.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${env:ALERT_EMAIL}
    alarms:
      - functionErrors
