service: youareawesomeapp
# app and org for use with dashboard.serverless.com
app: youareawesomeapp
org: prosingularity

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline # must come after typescript

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: prod

functions:
  reportInappropriate:
    handler: src/report-inappropriate.handler
    events:
      - http:
          path: "/reportinappropriate/"
          method: post
  registerPushNotif:
    handler: src/register-push-notification.handler
    events:
      - http:
          path: "/push-notifications/register/"
          method: post
    environment:
      CRON_JOB_NAME_PREFIX: "yaa-push-notifications-"
