### Lambda: Report Inappropriate

POST http://localhost:3000/prod/reportinappropriate
Content-Type: application/json

{"messageId":"test messsage id", "reason": "bad content", "comment": "testme"}

### Lambda: Subscribe to Push Notifications

PUT http://localhost:3000/prod/push-notifications/subscribe
Content-Type: application/json

{
    "token": "ExponentPushToken[98765]",
    "hour": 4,
    "minute": 51
}

### Lambda: Unsubscribe from Push Notifications
POST http://localhost:3000/prod/push-notifications/unsubscribe
Content-Type: application/json

{
    "token": "ExponentPushToken[98765]"
}

### Lambda: write contribution to Google Sheets
POST http://localhost:3000/prod/contributions
Content-Type: application/json

{
    "id": "32961b0a-8226-40cc-93d2-90313a70786c",
    "text": "hello there",
    "author": "I am author",
    "country": "from the country side",
    "isodate": "2020-05-10"
}
